export * from './TagsScreen/TagsScreen'
export * from './WordsScreen/WordsScreen'
export * from './TasksScreen/TasksScreen'
export * from './WordDescriptionScreen/WordDescriptionScreen'
export * from './NewWordScreen/NewWordScreen'
export * from './EditWordScreen/EditWordScreen'
