const DELETE_WORD = 'DELETE_WORD'
const EDIT_WORD = 'EDIT_WORD'
const ADD_TAG = 'ADD_TAG'
const EDIT_TAG = 'EDIT_TAG'
const EDIT_WORDS_LIST = 'EDIT_WORDS_LIST'
const DELETE_TAG = 'DELETE_TAG'
const DELETE_WORDS_LIST = 'DELETE_WORDS_LIST'
const SET_SETTINGS = 'SET_SETTINGS'

export {
  DELETE_WORD,
  EDIT_WORD,
  ADD_TAG,
  EDIT_TAG,
  EDIT_WORDS_LIST,
  DELETE_WORDS_LIST,
  DELETE_TAG,
  SET_SETTINGS,
}
