import { StyleSheet, } from 'react-native'

const styles = StyleSheet.create({
  container: {
    paddingTop: 15,
    paddingHorizontal: 7,
    paddingBottom: 50,
    backgroundColor: '#FFFFFF',
  },
  contentContainer: { alignItems: 'center', },
  definition: {
    marginTop: 5,
    textAlign: 'center',
    fontSize: 28,
    fontFamily: 'Norwester',
    color: '#FF8A00',
  },
  tagItem: {
    alignItems: 'center',
    justifyContent: 'center',
    marginHorizontal: 5,
    marginBottom: 5,
    marginTop: 3,
    paddingTop: 3,
    paddingBottom: 5,
    paddingHorizontal: 17,
    borderRadius: 20,
    borderWidth: 1,
    backgroundColor: '#DCDCDC',
    borderColor: '#808080',
  },
  activeTag: {
    backgroundColor: '#2d862d',
    borderColor: '#006600',
  },
  textStyle: { fontFamily: 'OpenSans', color: '#808080', fontSize: 20, },
  tagsBlock: {
    alignSelf: 'stretch',
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'center',
    marginVertical: 7,
    marginTop: 5,
  },
  selectAllBtn: { paddingHorizontal: 110, marginBottom: 35, },
  allTagsActive: { color: '#ffffff', },
  wordsBlock: {
    marginTop: 5,
    alignSelf: 'flex-start',
    flexDirection: 'row',
    alignItems: 'center',
  },
  valueStyle: {
    fontSize: 33,
    fontFamily: 'Chunkfive',
    color: '#404040',
  },
  inputStyle: {
    width: 120,
    paddingHorizontal: 10,
    justifyContent: 'center',
    backgroundColor: '#DCDCDC',
    borderWidth: 1,
    borderColor: '#787878',
    color: '#303030',
    fontSize: 25,
    borderRadius: 7,
    fontFamily: 'OpenSans',
  },
  orderItem: {
    width: 135,
    alignItems: 'center',
    justifyContent: 'center',
    marginHorizontal: 20,
    marginBottom: 5,
    marginTop: 3,
    paddingTop: 3,
    paddingBottom: 5,
    borderRadius: 20,
    borderWidth: 1,
    backgroundColor: '#DCDCDC',
    borderColor: '#808080',
  },
  editBtn: {
    marginTop: 30,
    marginBottom: 37,
    paddingVertical: 7,
    paddingHorizontal: 20,
    backgroundColor: '#D97604',
    borderWidth: 1,
    borderColor: '#ffcc80',
    borderRadius: 7,
  },
  editText: {
    color: 'white',
    fontSize: 30,
    fontFamily: 'FFF_Tusj',
  },
  alert: {
    marginTop: 4,
    color: '#b30000',
    fontSize: 16,
    fontFamily: 'PlayfairDisplay',
  },
  wordOrderStyle: { marginTop: 35, },
  activeOrderStyle: { color: '#ffffff', },
})

export default styles
